version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=api
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
  api:
    build:
      context: ./api-center
    volumes:
      - "./api-center:/workspace"
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    command: sh -c "/wait && /api-run"
    environment:
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
