version: '3'
services:
  mysql:
    build:
      context: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: giant
      MYSQL_PASSWORD: 123456
    container_name: api_db
    ports:
      - "3306:3306"
    tty: true
  api:
    build:
      context: ./api-center
    volumes:
      - "./api-center:/workspace"
    container_name: api_center
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - mysql   
   
